### ISSUE TITLE
Fork passport-oauth2-client-password

### ISSUE THREAD

**Issue by adamhathcock** [passport-next/passport-oauth2#3]
Hi,

I'm not sure where to put this but I'd like to have `passport-oauth2-client-password` forked into this org to use passport-vnext bits.

I'm happy to volunteer for maintenance of it and other things.  (Potentially `oauth2orize-openid` and others maybe)

Thanks!

**Comment by rwky** [comment]
I've forked the repo and done the intial migration https://github.com/passport-next/passport-oauth2-client-password

I've also sent you an invite to the org, feel free to fork any other passport related repos you like or contribute to any existing ones, if you need help or have any questions just yell. :smile:
